name: SmokeTest

permissions:
  pull-requests: write

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # at least support HEAD~1 for testing
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Prepare test source
        run: |
          curl -L  https://github.com/sourcegraph/lsif-go/releases/download/v1.9.3/src_linux_amd64 -o /usr/local/bin/lsif-go
          chmod +x /usr/local/bin/lsif-go
          lsif-go -v
      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -coverpkg=./...
      - name: Cmd Test
        run: |
          make
          ./srctx diff --outputCsv output.csv
          cat output.csv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: diffctx
        uses: williamfzc/diffctx@v0.1.3
        with:
          lang: "golang"
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
