name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          pkg: cmd/srctx
          dest: build
          prefix: srctx
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w
          buildmode: default

      - name: Command Level Test Prepare
        run: |
          cp build/srctx-linux-amd64 .
          chmod +x ./srctx-linux-amd64

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Command Level Test (Golang)
        run: |
          git clone https://github.com/gin-gonic/gin --depth=2
          cd gin
          ../srctx-linux-amd64 diff --withIndex --lang GOLANG --outputHtml ../sample.html
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/srctx-*
            sample.html
