name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          pkg: cmd/srctx
          dest: build
          prefix: srctx
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w
          buildmode: default

      - name: Build Extra Dep
        run: |
          # scip-java
          curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > coursier \
            && chmod +x coursier \
            && ./coursier setup -y \
            && ./coursier bootstrap --standalone --bat=true -o scip-java com.sourcegraph:scip-java_2.13:0.8.18 --main com.sourcegraph.scip_java.ScipJava
          
          # pack
          zip scip-java.zip ./scip-java ./scip-java.bat

      - name: Command Level Test
        run: |
          cp build/srctx-linux-amd64 .
          chmod +x ./scip-java
          chmod +x ./srctx-linux-amd64
          
          # golang
          ./srctx-linux-amd64 diff --withIndex
          
          # java/maven
          git clone https://github.com/williamfzc/sibyl --depth=2
          cd sibyl
          ../scip-java index -- clean package -DskipTests
          ../srctx-linux-amd64 diff --scip ./index.scip
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/srctx-*
            scip-java.zip
